version: '2'

services:
  frontend:
    image: App:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "80:80"
      - "5858:5858"
    volumes:
      - .:/src
    environment:
      - REMOTE_DEBUGGING
