version: '2'

services:
  hod-nilesh-kedare:
    image: hod-nilesh-kedare:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/src
    environment:
      - REMOTE_DEBUGGING
